services:
  app:
    build: .
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
          ignore:
            - node_modules/